name: CPSCheckAAC
version: ${version}
main: com.danifoldi.cpscheckaac.CPSCheckAAC
authors:
  - DaniFoldi
website: danifoldi.com
description: Check CPS of players
api-version: 1.13
depend:
  - AAC5
  - ProtocolLib
permissions:
  cpscheckaac.reload:
    description: Permission to reload the configuration
commands:
  cpscheckaac:
    description: Used to reload the plugin
    usage: /<command> reload